version: '3.8'

services:
  app:
    image: my-app:latest  # Имя образа, которое вы строите с помощью docker build
    container_name: my-app-container
    restart: always
    ports:
      - "80:3000"  # Прокси-сервер на порту 80 будет направлять трафик на порт 3000 в контейнере
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app  # Монтируем текущую директорию на контейнер
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
