steps:
  - name: Greet the User
    run: echo "Hello World!"
  # List all files in the current directory for comparison before and after actions/checkout@v2.
  - run: ls -l
  - uses: actions/checkout@v2
  - run: ls -l
